name: Build From Scratch

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - name: Build
      run: |
        sudo chown -R runner /nix
        cd && git clone https://github.com/sayanarijit/.files && cd .files && make
