name: Build From Scratch

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        nix-path: nixpkgs=channel:nixos-unstable
    - name: "Build & Test"
      run: |
        cd && git clone https://github.com/sayanarijit/.files && cd .files && make
