name: Run All Installations

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run help command.
      run: |
        cd && git clone https://github.com/sayanarijit/.files && cd .files && make
